### ISSUE TITLE
Contribution towards Competitive Code Problems

### ISSUE THREAD

**Issue by asingh4451** [JenilGajjar20/Competitive-Programming_problems#6]
@JenilGajjar20 I would like to contribute to competitive coding problems That I have solved on Leetcode as well as Geeks for Geeks Kindly allow me

**Comment by JenilGajjar20** [comment]
Hey, @asingh4451. Kindly read the contributing guidelines [here](https://github.com/JenilGajjar20/Competitive-Programming_problems/blob/master/CONTRIBUTING.md). 

Are you contributing as a part of **hacktoberfest**?

**Comment by asingh4451** [comment]
Yes As a part of hackoctoberfest

**Comment by JenilGajjar20** [comment]
You can contribute @asingh4451. I hope you have gone through the contributing guidelines. 

Happy Hacking 🚀

**Comment by nancy-singh10** [comment]
hey plz assign me this work under hacktoberfest 2023 .

**Comment by kash5811** [comment]
hey please assign me this under hacktoberfest 2023

**Comment by athu070** [comment]
@JenilGajjar20 I would like to contribute to competitive coding problems. Please assign me this under hacktoberfest 2023

**Comment by JenilGajjar20** [comment]
@athu070, @kash5811, and @nancy-singh10 please go through the guidelines once before you proceed further.

Happy hacking 🚀

**Comment by ArionDas** [comment]
@JenilGajjar20 please assign me to this task for hacktoberfest, I can contribute a lot of algorithms and codes related to competitive programming in c++...

**Comment by barkhayadav12** [comment]
Hi, I would like to work on this. Can you please assign it to me under hactoberfest 2023?

**Comment by MOHIT-PANDEY215** [comment]
Hey @JenilGajjar20 I would like to contribute. Please assign me.

**Comment by Abhi01goenka** [comment]
Hello @JenilGajjar20 
I have solved many problems on Leetcode and Codeforces and I would like to contribute in this repository under hacktoberfest-2023. 
Please assign me.

**Comment by AdityaSrivastav5** [comment]
please assign me . I have done a ton of problems on leetcode and i wanna contribute in hacktoberfest

**Comment by sadhiin** [comment]
Hi 👋🏼 please assign me, under hacktoberfest-2023.
Regards...

**Comment by AdityaSrivastav5** [comment]
PLEASE MERGE PULL REQUEST AND GIVE HACKTOBERFEST ACCEPTED LEBEL

**Comment by JenilGajjar20** [comment]
> PLEASE MERGE PULL REQUESTS OF EVERYONE AND GIVE HACKTOBERFEST ACCEPTED LEBEL

@AdityaSrivastav5 Please check your **PRs** again. I have asked you to modify it as per the guidelines.

**Comment by parasjain123** [comment]
Hi. Please assign me this under hacktoberfest accepted label.

**Comment by parasjain123** [comment]
Hi. Please review my PR

**Comment by ShivanshDengla** [comment]
Hi, created a pull request, please let me know if any changes are required - https://github.com/JenilGajjar20/Competitive-Programming_problems/pull/49

**Comment by JenilGajjar20** [comment]
> Hi, created a pull request, please let me know if any changes are required - #49

https://github.com/JenilGajjar20/Competitive-Programming_problems/pull/49#pullrequestreview-1661611331

**Comment by RAGHAVS1304** [comment]
Hlo @JenilGajjar20 i keep solving problems in CPP. Please assign me this issue.
Thanks.

**Comment by suryansh98** [comment]
Hey, I would like to contribute to the problems, can you assign it to me.

**Comment by dipanwita1405** [comment]
hey please assign me this under hacktoberfest 2023

**Comment by dipanwita1405** [comment]
Hey please assign me, under hacktoberfest-2023.

**Comment by DNA5769** [comment]
Hey, can you assign me this issue under hacktoberfest

**Comment by chandraparsad3** [comment]
Hey, I would like to contribute to the problems, can you assign it to me.

**Comment by avinashyadav16** [comment]
hey @JenilGajjar20 !!
I would like to contribute to **Leetcode competitive coding problems** that I have solved on the platform. Requesting you to please assign me as a part of **hacktoberfest 2023.**

**Comment by lupefu** [comment]
@JenilGajjar20  I would like to contribute to competitive coding problems. Please assign me this under hacktoberfest 2023

**Comment by chandraparsad3** [comment]
I have contributed another problems i request you to please assign me as apart of hacktoberfest  2023

**Comment by l3vith** [comment]
Hi, I want to contribute to this repository and add some of the problems I know how to solve. Please assign me as a part of Hacktoberfest 2023
