### ISSUE TITLE
Updating README.md

### ISSUE THREAD

**Issue by anmol420** [JenilGajjar20/Competitive-Programming_problems#62]
The Readme File Of The Repository Is Quite Simple. So, want to transform it into a vibrant looking Readme.

Some Of The Additions Are - 
- Addition Of Emojis 
- Changes In Text Content
- Change In Format

Please  Assign Me The Issue !

**Comment by SuryaCreatX** [comment]
Can you assign me this issue?

**Comment by JenilGajjar20** [comment]
> Can you assign me this issue?

Specify your changes @SuryaCreatX

**Comment by anmol420** [comment]
> Can you assign me this issue?

This issue has already been assigned to me !
